AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3Website ACM Cert. and CloudFront Distro.'

Parameters:
  DomainName:
    Type: String
    Default: xxxxxxxx.com
    Description: The domain name for the website

  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: The Route 53 Hosted Zone ID

  S3BucketsStackName:
    Type: String
    Description: Name of the S3 buckets CloudFormation stack

  LogsBucketName:
    Type: String
    Description: Name of the S3 bucket for logs

  SiteBucketName:
    Type: String
    Description: Name of the S3 bucket for the website

  TagKey:
    Type: String
    Description: Key for resource tagging

  TagValue:
    Type: String
    Description: Value for resource tagging

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames: 
        - !Ref DomainName
        - !Sub "www.${DomainName}"
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Sub "www.${DomainName}"
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "OAC for ${DomainName}"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        PriceClass: PriceClass_100
        Logging:
           Bucket: !Sub "${LogsBucketName}.s3.amazonaws.com"
           IncludeCookies: false
           Prefix: CloudFrontLogs/
        Aliases:
          - !Ref DomainName
          - !Sub "www.${DomainName}"
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - DomainName: !Sub "${SiteBucketName}.s3.amazonaws.com"
            Id: S3Origin
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
            S3OriginConfig: {}
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: /error.html
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue

  Route53RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
      - Name: !Ref DomainName
        Type: A
        AliasTarget:
          DNSName: !GetAtt Distribution.DomainName
          EvaluateTargetHealth: false
          HostedZoneId: Z2FDTNDATAQYW2
      - Name: !Sub "www.${DomainName}"
        Type: A
        AliasTarget:
          DNSName: !GetAtt Distribution.DomainName
          EvaluateTargetHealth: false
          HostedZoneId: Z2FDTNDATAQYW2
    DependsOn: 
      - Distribution

Outputs:
  CertificateArn:
    Description: Issued certificate
    Value: !Ref Certificate
  CloudFrontOACId:
    Description: ID of the CloudFront Origin Access Control
    Value: !Ref CloudFrontOriginAccessControl
    Export:
      Name: CloudFrontOACId
  CloudFrontDistributionId:
    Description: "CloudFront Distribution ID"
    Value: !Ref Distribution
    Export:
      Name: DistributionId
  CloudFrontStackName:
    Description: "Name of the CloudFront Stack"
    Value: !Ref AWS::StackName
    Export:
      Name: CloudFrontStackName