# Name of the workflow
name: Destroy Site

# Define when this workflow will run
on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branches:
      - main  # Runs on pushes to the main branch

# Define environment variables that will be available to all jobs
env:
  AWS_REGION: 'us-east-1'  # Set the AWS region for destruction
  WEBSITE_URL: ${{ secrets.WEBSITE_URL }}  # URL of the website to verify after destruction

# Define the jobs that will run as part of this workflow
jobs:
  SiteKill:
    if: "contains(github.event.head_commit.message, 'destroy-site')"  # Trigger destruction only if commit message contains 'destroy-site'
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    timeout-minutes: 30  # Set a 30-minute timeout for the entire job

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3  # Use the latest stable version of the checkout action

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3  # Use the latest stable version of the setup-node action
        with:
          node-version: '20'  # Use Node.js version 20

      # Step 3: Cache npm dependencies to speed up installation
      - name: Cache dependencies
        uses: actions/cache@v3  # Use the latest stable version of the cache action
        with:
          path: ~/.npm  # Specify the path to cache
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}  # Create a cache key based on OS and package-lock.json
          restore-keys: |
            ${{ runner.OS }}-node-  # Fallback to using the latest cache if no exact match is found

      # Step 4: Install project dependencies
      - name: Install dependencies
        run: npm ci  # Use 'ci' for clean install, respecting package-lock.json

      # Step 5: Configure AWS credentials securely
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2  # Securely configure AWS credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 6: Tear Down Site
      - name: Tear Down Site
        run: |
          echo "Starting site destruction..."
          ./bin/website-destroy  # Run your custom destruction script
          echo "Site destruction complete."

      # Step 7: Verify the destruction
      - name: Verify destruction
        run: |
          # Use the WEBSITE_URL environment variable with a 30-second timeout
          response=$(curl -s -o /dev/null -w "%{http_code}" --max-time 30 ${{ env.WEBSITE_URL }})
          if [ "$response" -eq 404 ] || [ "$response" -eq 000 ]; then
            echo "Destruction verified successfully"
          else
            echo "Destruction verification failed with status code: $response"
            exit 1
          fi

      